name = "sww-comments"
account_id = "99ffb024723930ef9a74ee7bbd09c82c"
main = "comments-worker.js"
compatibility_date = "2024-01-01"

# KV Namespace binding
[[kv_namespaces]]
binding = "COMMENTS_KV"
id = "4de0b8ce5f47423b9711d41987b71533"
