name = "sww-comments"
account_id = "85eadfbdf07c02e77aa5dc3b46beb0f9"
main = "comments-worker.js"
compatibility_date = "2024-01-01"

# KV Namespace binding
[[kv_namespaces]]
binding = "COMMENTS_KV"
id = "ddf6162d4c874d52bb6e41d1c3889a0f"

# Cron trigger - rebuild cache every minute (Cloudflare limitation)
# Will run 20 rebuilds per minute for 3-second intervals
[triggers]
crons = ["* * * * *"]
