name: Deploy to Cloudflare Workers

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy to Cloudflare Workers
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build Next.js app
        run: npm run build
        env:
          NEXT_PUBLIC_COMMENTS_API: ${{ vars.NEXT_PUBLIC_COMMENTS_API }}
          NEXT_PUBLIC_R2_BUCKET_URL: ${{ vars.NEXT_PUBLIC_R2_BUCKET_URL }}
        
      - name: Install Wrangler
        run: npm install -g wrangler@3.114.14
        
      - name: Deploy Comments Worker
        run: |
          cd workers
          wrangler deploy
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          
      - name: Deploy Main Site to Workers
        run: wrangler deploy --compatibility-date=2024-01-01
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          
      - name: Display URLs
        run: |
          echo "✅ Deployment complete!"
          echo "Main site: https://saywhatwant.app"
          echo "Workers URL: https://say-what-want.bootloaders.workers.dev"
          echo "Comments API: https://sww-comments.bootloaders.workers.dev"
